apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-news-dev-config
data:
  redis_port: "6379"
  redis_host: "rs-redis-cluster-news-dev.bzodip.0001.apse1.cache.amazonaws.com"
  messge_broker_redis_port: "6379"
  messge_broker_redis_host: "redis-cart"
  aws_region: "ap-southeast-1"
  s3_bucket: "aws-gcr-rs-sol-dev-ap-southeast-1-522244679887"
  s3_prefix: "sample-data-news"
  click_record_file_path: 'sample-data-news/system/ingest-data/action/'
  user_record_file_path: 'sample-data-news/system/ingest-data/user/'
  click_record_bucket: 'aws-gcr-rs-sol-dev-ap-southeast-1-522244679887'
  local_data_folder: '/rs-data/news-dev/'
  aws-exports.json: |
    {
      "DEPLOY_TYPE": "ALL",
      "NEWS_API_URL": "http://adf45c54cf8734c0f9c14f4adfecae86-234454018.ap-southeast-1.elb.amazonaws.com/api/v1/demo",
      "MOVIE_API_URL": "http://a4fb68ded64b0495f90bbaa36c7773cd-1545468192.ap-southeast-1.elb.amazonaws.com/api/v1/demo"
    } 

  
