apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: rs-news-dev-ns

resources:
- config.yaml
- gateway.yaml
- ./efs/pv-claim.yaml
- ../../loader
- ../../filter
- ../../portrait
- ../../rank
- ../../recall
- ../../redis
- ../../event
- ../../retrieve
- ../../demo
- ui
- ../../personalize

# all with following *kustomization*
images:
- name: rs/demo
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/demo
  newTag: afb5c424c9271044c01c6f865a9bb0a79247d0ed
- name: rs/event
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/event
  newTag: 26edea606f182e289c1a6fc7394a35209a052b86
- name: rs/filter
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter
  newTag: 25f170269e3288d5fbe6c20d02557c5c000e1c96
- name: rs/filter-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/filter-plugin
  newTag: news-25f170269e3288d5fbe6c20d02557c5c000e1c96
- name: rs/loader
  newName: public.ecr.aws/t8u1z3c8/rs/loader
  newTag: latest
- name: rs/personalize
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/personalize
  newTag: 70ce93340bd476f190c565af7f04dbd6b43d17f8
- name: rs/portrait
  newName: public.ecr.aws/t8u1z3c8/rs/portrait
  newTag: latest
- name: rs/portrait-plugin
  newName: public.ecr.aws/t8u1z3c8/rs/portrait-plugin
  newTag: latest
- name: rs/rank
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank
  newTag: a95248599c277f4e62d51e87c6b1ecb8136e58d3
- name: rs/rank-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/rank-plugin
  newTag: news-a95248599c277f4e62d51e87c6b1ecb8136e58d3
- name: rs/recall
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall
  newTag: 442c0559a27f105f39749899f3f6a4f5f2f42ede
- name: rs/recall-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/recall-plugin
  newTag: news-442c0559a27f105f39749899f3f6a4f5f2f42ede
- name: rs/retrieve
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/retrieve
  newTag: 3348e5693b98b88bb87eee52d9c20c766502d7e9
- name: rs/retrieve-plugin
  newName: 466154167985.dkr.ecr.ap-northeast-1.amazonaws.com/rs/retrieve-plugin
  newTag: news-personalize-3348e5693b98b88bb87eee52d9c20c766502d7e9
- name: rs/ui
  newName: public.ecr.aws/t8u1z3c8/rs/ui
  newTag: latest



vars:
- fieldref:
    fieldPath: data.redis_host
  name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.redis_port
  name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_host
  name: MESSGE_BROKER_REDIS_HOST
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.messge_broker_redis_port
  name: MESSGE_BROKER_REDIS_PORT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.aws_region
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_bucket
  name: S3_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.s3_prefix
  name: S3_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_bucket
  name: CLICK_RECORD_BUCKET
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.click_record_file_path
  name: CLICK_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.user_record_file_path
  name: USER_RECORD_FILE_PATH
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
- fieldref:
    fieldPath: data.local_data_folder
  name: LOCAL_DATA_FOLDER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: rs-news-dev-config
