apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels: 
        app: ui
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: rs-dev-workshop-ui
        image:  rs-dev-workshop/ui:latest
        ports:
          - name: http
            containerPort: 80
        resources:
          requests: 
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
