apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: recommender-system-v2
  region: ap-northeast-1
  version: "1.18"


nodeGroups:
  - name: recommender-system-ng-v2
    labels: { role: recommender-system-ng-v2 }
    instanceType: r6g.4xlarge
    minSize: 3
    maxSize: 6
    volumeSize: 80
    ssh:
      allow: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      withAddonPolicies:
        imageBuilder: true
        externalDNS: true
        certManager: true
        ebs: true
        fsx: true
        efs: true
        appMesh: true
        xRay: true
        autoScaler: true
        albIngress: true
        cloudWatch: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/recommender-system-v2: "owned"
  # - name: recommender-system-ng-gpu
  #   labels: { role: recommender-system-ng-gpu }
  #   instanceType: p3.8xlarge
  #   minSize: 1
  #   maxSize: 2
  #   volumeSize: 160
  #   ssh:
  #     allow: true
  #   iam:
  #     withAddonPolicies:
  #       imageBuilder: true
  #       externalDNS: true
  #       certManager: true
  #       ebs: true
  #       fsx: true
  #       efs: true
  #       appMesh: true
  #       xRay: true
  #       autoScaler: true
  #       albIngress: true
  #       cloudWatch: true
