apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:11.0-base
    args:
    - "nvidia-smi"
  nodeSelector:
    alpha.eksctl.io/nodegroup-name: "rs-gpup3-ng"
  tolerations:
  - key: "feaster"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
