apiVersion: v1
kind: ConfigMap
metadata:
  name: __CONFIG-MAP-NAME__
data:
  redis_port: "6379"
  redis_host: "__ELASTIC-CACHE-REDIS__"
  messge_broker_redis_port: "6379"
  messge_broker_redis_host: "redis-cart"
  aws_region: "__REGION__"
  s3_bucket: "__S3-BUCKET__"
  click_record_file_path: '__S3-BASE-FOLDER__/system/ingest-data/action/'
  user_record_file_path: '__S3-BASE-FOLDER__/system/ingest-data/user/'
  local_data_folder: '/rs-data/__LOCAL_DATA_FOLDER__/'
  
