apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-movie-dev-config
data:
  redis_port: "6379"
  redis_host: "rs-redis-cluster-movie-dev.bzodip.0001.apse1.cache.amazonaws.com"
  messge_broker_redis_port: "6379"
  messge_broker_redis_host: "redis-cart"
  aws_region: "ap-southeast-1"
  s3_bucket: "aws-gcr-rs-sol-dev-ap-southeast-1-522244679887"
  s3_prefix: "sample-data-movie"
  click_record_file_path: 'sample-data-movie/system/ingest-data/action/'
  user_record_file_path: 'sample-data-movie/system/ingest-data/user/'
  click_record_bucket: 'aws-gcr-rs-sol-dev-ap-southeast-1-522244679887'
  local_data_folder: '/rs-data/movie-dev/'  
  aws-exports.json: |
    {
      "DEPLOY_TYPE": "MOVIE",
      "NEWS_API_URL": "/api/v1/demo",
      "MOVIE_API_URL": "/api/v1/demo"
    }  
