apiVersion: v1
kind: PersistentVolume
metadata:
  name: __EFS-PV__
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: __EFS-SC__
  csi:
    driver: efs.csi.aws.com
    # volumeHandle: fs-b2ab7ef2
